### ISSUE TITLE
test lumins::core::test_synchronize::dir_2 ... FAILED

### ISSUE THREAD

**Issue by mxork** [wchang22/LuminS#21]
on a clean v0.3.0 checkout, `cargo test --release --locked` fails:

```
---- lumins::core::test_synchronize::dir_2 stdout ----
thread 'lumins::core::test_synchronize::dir_2' panicked at 'assertion failed: `(left == right)`
  left: `false`,
 right: `true`', src/lumins/core.rs:227:9
```

with `cargo test --locked` (no `--release`), it passes.

I'm putting together an AUR package and it would be nice to have a clean slate of tests. 

running this from an up to date Archlinux box.

**Comment by wchang22** [comment]
Thanks for the issue, #22 should fix this.
