### ISSUE TITLE
Windows binary

### ISSUE THREAD

**Issue by SmuSmu** [wchang22/LuminS#27]
Hi,

I found your repo yesterday. Great stuff.

How about automatic windows binaries during every release. Would love to help out with a msi installer. Did this already in one of my projects.

Would love to do that if you put an hacktoberfest label on this issue ;)

**Comment by ErisMik** [comment]
Sure, I'd love to make that happen. I'll have to get permission from the owner, so it might take a few days to get that set up.

**Comment by ErisMik** [comment]
Sorry about the delay, I was moving and very busy. I also originally misread your issue. I have added the hacktober label to the issue. Let me know if you need anything else from me.

**Comment by sergeevabc** [comment]
Releases section is still empty. Where do I download a binary for Windows?
